---
version: '3.6'
services:

  redis-db:
    image: redis:3.2.5-alpine
    command: redis-server
    ports:
      - 6377:6379
  postgres-db:
    network_mode: bridge
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=address_db
    ports:
      - '5433:5432'
  redis-commander-cli:
    container_name: redis-commander-cli
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8082:8082"
#  agent:
#    container_name: newrelic-infra
#    image: newrelic/infrastructure:latest
#    cap_add:
#      - SYS_PTRACE
#    network_mode: host
#    pid: host
#    privileged: true
#    volumes:
#      - "/:/host:ro"
#      - "/var/run/docker.sock:/var/run/docker.sock"
#    environment:
#      NRIA_LICENSE_KEY: "0fc9dd7512b48399e3129c4d1ebe2f0f7bc6NRAL"
#    restart: unless-stopped



